spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
server:
  port: 8081
  servlet:
    context-path: /api

springdoc:
  show-actuator: true
  packages-to-scan: "com.tw.prograd"

storage:
  initialize: true
  location: images